#!/usr/bin/env bash
# This is a launcher script for use on Linux, MacOS and other UNIX variants.
# It checks that uv is installed then runs the script in a python virtual environment.
set -o pipefail
which -s uv
if [ $? -ne 0 ]; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi
uv run ./rrscrape.py
