#!/usr/bin/env bash
# This is an installer script for use on Linux, MacOS and other UNIX variants.
# It ensures that 'uv' is installed and that the project has a virtual environment.
# It should be run once before running the rrscrape script.
which -s uv
if [ $? -ne 0 ]; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi
set -e
if [ ! -d .venv ]; then
    uv venv
    source .venv/bin/activate
    uv pip install -r pyproject.toml
fi
